name: "OpenCCU Multicast Relay"
version: "0.3.14"
stage: experimental
slug: "openccu-multicast-relay"
description: "relays Homematic IP HAP and Homematic IPW DRAP link-local multicast between newtork and OpenCCU app instance"
url: "https://github.com/grunes/home-assistant-addons/openccu-multicast-relay"
arch:
  - aarch64
  - amd64
init: false
startup: system
realtime: true
host_network: true
privileged:
  - NET_ADMIN
options:
  multicast_groups:
    - "224.0.0.120:43438"
    - "224.0.0.1:43439"
  source_interface: ""
  target_interface: ""
  log_level: "info"
schema:
  multicast_groups:
    - str
  source_interface: "str?"
  target_interface: "str?"
  log_level: "list(debug|info|warning|error)"
