name: DokuWiki
arch:
- aarch64
- amd64
description: The OpenSource Wiki Software on your Home Assistant
image: docker.io/dokuwiki/dokuwiki
version: 2025-05-14b
slug: dokuwiki
init: false
ingress: true
ingress_port: 8080
ingress_entry: /ead0423c_dokuwiki
ingress_stream: false
panel_title: DokuWiki
panel_icon: mdi:book-open-page-variant
backup: hot
map:
  - data:/storage
  - addon_config:/var/www/html/conf
environment:
  PHP_TIMEZONE: Europe/Berlin
url: https://hub.docker.com/r/dokuwiki/dokuwiki/tags?ordering=name
#ports:
#  8000/tcp: 8080
#ports_description:
#  8080/tcp: HTTP
#webui: http://[HOST]:[PORT:8080]
